lux-group/router

lib/generate-swagger.js, test/integration/router.test.js
express is `:id` wheras swagger is `{id}`
this will allow us to use swagger ui with actual input
=> Fix path parameters

README.md, index.d.ts, lib/router.js
To aid collaboration I would like ability to expose swagger on deployed sites - but behind auth and only for admin accounts.
Clients could then pass auth middleware in the swagger opts e.g. routes.js:
```
const { router } = require('@luxuryescapes/router')
const checkValidToken = require('./middleware/check-valid-token')
const requireAdmin = require('./middleware/requires-admin')
exports.mount = app => {
...
const routerAbstraction = router(app, {
validateResponses: config.get().validateResponses,
swaggerBaseProperties: {
swagger: '2.0',
...
preHandlers: [checkValidToken, requireAdmin] 
}
})
...
routerAbstraction.serveSwagger('/api/docs/<service-name>')
return routerAbstraction
}
=> Add prehandlers to swagger

index.d.ts
Without this we can get an eslint error when trying to throw
=> fix(types): extend Error for HTTPError class

index.d.ts
Because `next` is not actually optional, and it has it's own definition that isn't just `Function`.
=> Use express' Handler type

.circleci/config.yml, index.d.ts, lib/generate-swagger.js, lib/router.js, test/integration/router.test.js
* Adds operationIds to the schema https://swagger.io/docs/specification/paths-and-operations/
* Accept handlers with their own type specifications
* Fix issue with CircleCI cache (not sure why this started failing now)
=> OpenAPI Schemas should have operationIDs

lib/middleware/error-handler.js
Previous Behaviour:
* Unhandled exceptions are logged to the console
* Handled HTTP errors are not logged to the console
New Behaviour
* Unhandled exceptions are logged to the console
* Handled server errors are logged to the console
* Other handled http errors are not logged to the console
An example of where this makes a difference: https://github.com/lux-group/svc-public-offer/blob/master/src/utils/request/responseInterceptor.js#L5
Because we're explicitly throwing a ServerError, the details don't get logged. IMO they should because an unexpected event has occurred and it's useful to be able to see the stack trace.
THAT ALL SAID - there's probably an argument for not throwing the server error like we are in Public Offer. This library is responsible for API level logic, whereas its …
=> Ensure we console.error all server errors

lib/middleware/error-handler.js
Following on from https://github.com/lux-group/router/pull/25 - we should still log the original error! Otherwise its stack trace is lost to the abyss.
=> Make sure we log the original error

lib/generate-swagger.js, test/integration/router.test.js
As per the spec, arrays can have items which describe the type inside.
=> Generate OpenAPI correctly for array items

lib/generate-swagger.js, package.json, test/generate-swagger.test.js
We're not generating definitions for schemas inside oneOf matchers. With this change, we do.
=> Generate definitions for oneOf

.circleci/config.yml, README.md, lib/generate-swagger.js, lib/router.js, lib/utils/uuid.js, package.json, test/integration/router.test.js
We want to be able to provide a size limit on the JSON payloads per endpoint.
This PR adds the JSON middleware to all handlers and allows options to be passed to it.
So you would do:
```
router.put({
url: '/api/passport-details',
jsonOptions: { limit: '20mb' },
handler...
})
```
Also replaced uuid dependency with native crypto module and made Node 14 a requirement.
=> Allow json options to be passed per route

README.md, index.d.ts, lib/generate-swagger.js, package.json, test/generate-swagger.test.js, test/generate-types.test.js, test/integration/router.test.js
OpenAPI v3 has been out for a long time now and we should support it as it has some new features like `oneOf`. When we want to improve the functionality of the OpenAPI generation its better if we can do so against v3 rather than doing it against v2 and then having to rework it later. There are some significant differences for things like query params.
API Docs will be generated against v3 of the specification.
Auto generated types will have their "definitions" moved under "components".
Relatively minor changes to meet the v3 spec. Some code could actually be deleted because the v3 spec is closer to JSON schema than v2. Added additional tests where the transformation need to change. Also introduced `openapi-schema-validator` as a dev dependency to validate the output.
One thing to note is …
=> Generate API spec as OpenAPI v3.0.3 

lib/generate-swagger.js, package.json, test/generate-swagger.test.js
Before this change, we're not adding definitions for matchers that are used in hashmaps. Now we do.
Tested as well by running against the public offer schemas and observing only the expected differences.
=> Add definitions for hashmap

README.md, index.d.ts, package.json, test/generate-types.test.js
From https://github.com/lux-group/svc-public-offer/blob/master/src/api/common/types.ts
A helper type that allows you to type your Express handler functions according to the autogenerated types.
An example can be seen here: https://github.com/lux-group/svc-public-offer/blob/master/src/api/v2/controllers/offer.ts#L70
=> Add handler type for autogenerated types

README.md, generate-types.js, lib/generate-types.js, package.json
This removes the need for boilerplate code in the services to hook up the generateTypes functionality.
Kudos to @alecluxuryescapes for the push to get this over the line.
See README for further info.
=> Add generateTypes CLI command

README.md, generate-types.js, package.json
* Change `yarn generateTypes` to be `yarn router:generateTypes` so that projects can implement their own `yarn generateTypes`
* Fixes the `ci` option.
=> Fix generateTypes ci option

index.d.ts, package.json, tsconfig.json
When you use the verifyUser Express middleware from lib-auth-middleware, it ensures an authenticated user is present and a couple of properties get added to the Request - `user` and `jwt`.
TypeScript doesn't recognise this and there are various awkward workarounds to make this work. This PR makes the user and jwt properties to be available automatically when used with auto generated types.
If a route is public, there will be a Cookie header in the OpenAPI schema and in the autogenerated types and this is trigger for the properties to be there.
So in your routes, if you say `isPublic: true`, the jwt and user properties will not be there, and when `isPublic: false`, the properties will be there.
=> Add authenticated request type

generate-types.js, package.json
This handles the case where there is a JS error in your code and you try to generate types. The process is already resilient to TypeScript type errors.
=> Handle syntax errors when generating types

generate-types.js, package.json
When generating types, often the user would want the package to auto increment. This changes increments the package.json if the types have changed.
In the case of CI, incrementing is disabled.
=> Include in usage optional auto increment of package

index.d.ts, package.json
I noticed that if you forget to specific a path param in the Strummer schema, it appears in the Controller as `never`. And it turns out you can pass `never` to functions and TypeScript doesn't complain!
Before:
After:
=> When handler params are not defined, it should give the empty object

lib/generate-swagger.js, package.json, test/integration/__snapshots__/router.test.js.snap, test/integration/router.test.js
Mutating the data means that if you run generateSwagger again, you get a different result. Very tricky bug!
Use `omit` instead. We could write our own rather than using Lodash's. No strong opinions here. If this was TypeScript I'd recommend using Lodash so that we get the right type behaviour, but since this is JS 🤷
=> Use omit instead of mutating

lib/generate-server-types.js, lib/generate-types.js, package.json, test/generate-types.test.js
This will allow us to generate the correct type for a custom matcher that we have in one of our services
Currently the json schema of the matcher looks like
```
{
type: ["null", "string"]
}
```
(and is totally valid json schema apparently see [this section](https://json-schema.org/draft/2020-12/json-schema-core.html#rfc.section.7.6.1))
and it needs to stay this way as Admin Portal uses this to auto generate html forms
which gets generated as `fieldName: unknown` when running `generateTypes` but we should expect to see `fieldName: null | string`
although it would be nice if this code got passed in from the external codebase into router, it seems non trivial to do so seeing as though we are using the generate types task as a cli command, we would have to essentially eval some javascript …
=> feat(types): handle null or string type

generate-types.js, package.json
Noticed that CI was not failing when changes to the contract had not been committed
It was because we were not returning whether there are `pendingCommits` when it's in CI mode
=> fix(server-types): fix ci option for checking whether there are type changes

lib/sentry.js, package.json
When running tests the this lib logs out the following constantly:
```
warn: No Sentry DSN configured, skipping initialization.
```
This makes it so the warning only outputs in produciton.
=> silence no sentry log info for tests

package.json
https://aussiecommerce.atlassian.net/browse/ENGX-540
svc-flights-amadeus is using our own @luxuryescapes/router library that brings a transient dependency swagger-ui-dist that has a security issue.
Instead of adding a resolution we should update @luxuryescapes/router so it depends on the later version of swagger-ui-dist.
=> [ENGX-540] Update swagger to latest

lib/generate-server-types.js, package.json, test/generate-types.test.js
The is an interesting PR proposal. Unfortunately the svc-tour data import from conn-ttc has the `Date` type for a lot of date fields. I'm currently building another data sync for conn-salesforce and need to use the said import contract.
https://github.com/lux-group/svc-connection-tour-salesforce/pull/11
The correct type should be ISODate string and we intend to migrate to this.
In the meantime, I want to generate the `Date` type by the following method. Is this too hacky? Open to better suggestions.
=> Add generate date type

index.d.ts
`aud` is used for the agent ID when spoofing a user's account.
=> Add missing `aud` property to `Jwt` type

lib/generate-server-types.js, package.json
If a custom string field matcher specifies `format: 'time'`, leave it as `string` when generating TS types.
Fixes this undesired type generation: https://github.com/lux-group/svc-trip/pull/285#issuecomment-1307891493
(I suspect what we really need is a way for services to specify how their schema fields should be translated to TS types, rather than having it centrally defined in the router package.)
=> Fix type generated for string with time format

lib/errors/HTTPError.js, package.json
Sentry logs all errors with 'status' fields >= 500.
Out router Errors didn't have 'status' fields.
This should fix it
=> Adding status field to error objects (should let Sentry handling them

README.md, lib/middleware/error-handler.js, lib/router.js, package.json, test/integration/router.test.js
currently when a express app throws a exception within a request - response cycle the output
is logged using console, this PR enables us to use the luxuryescapes lib-logger
to log these expections.
As it stands console log will log the stack trace within new relic, but because the
stack trace is a string with many new line chars within it it appears as many log
lines in new relic, with this change it will only appear as one line which will contain
the key **stack** the value of which will be the stack trace.
I have also added the http_method, http_status (which I believe in all cases will be 500) and http_path
this will bring the log message  in line with the access log messages produced by the heroku router.
As it stand in order to get the stack trace for any 500 error code you need to …
=> using lib logger to format errors in new relic

README.md, index.d.ts, lib/sentry.js, lib/utils/sanitizer.js, lib/utils/sanitizer.spec.js
This PR allows us to scrub sensitive personal information on Sentry error logging.
Before:
https://luxury-escapes-9m.sentry.io/issues/3955688380/events/6f9c45b6e01f4f4f8a70ac98a5f00af5/?project=4504138441818112
You can see the body contains the traveller's name:
After:
With the following settings:
https://luxury-escapes-9m.sentry.io/issues/3955688380/events/1feb397b336246728a80bdfbecd9df1e/?project=4504138441818112
You can see the traveller's name is hidden with ***
=> ENGX-711: Add `sanitizeKeys` attribute to stop passing PI to Sentry.

lib/middleware/async.js, lib/middleware/error-handler.js, lib/middleware/network-logger.js, lib/middleware/request-validator.js, lib/middleware/response-validator.js, package.json
Change middleware to named functions.
This is so Spans in newrelic can be named correctly rather than being called annoymous.
=> change middleware to named functions

lib/middleware/request-validator.js, package.json
This PR fixes the issue that sometime the logging would miss the data.
As the project may use Winston as the logger, which does not support logging a string message from the second parameter, which is expected to be an object. So the logging as follows does not include the details in the log message:
`logger.warn('[VALIDATION WARNING] Invalid payload', JSON.stringify(errors))`
Output:
`{"label":"test","level":"warn","message":"[VALIDATION WARNING] Invalid payload","service":"test-le-svc-cart"}`
New Relic:
After the fixing:
Output:
=> NOJIRA: Fix logging information missing

index.d.ts, package.json
It's not always clear what the various route options mean. This PR adds some tsdoc comments to make it easier to find out.
=> Add tsdoc comments to `RouteOptions`

lib/router.js, package.json
Currently, all middleware is labelled as `asyncMiddleware`. See screenshot below.
This PR rewrites the wrappedMiddleware back to the original middleware name to enable better performance tracing.
**Before**
**After**
=> fix middleware names in spans

index.d.ts, package.json
https://aussiecommerce.atlassian.net/browse/CONLT-1564
While implementing this story, we found the interface described for HTTPError hadn't been updated to match the interface.
=> [CONLT-1564] feat(errors): updated interface to match implementation

index.d.ts, package.json
The current types are setup for compatibility with verifyUserSignature. For most use cases outside of auth, we use the verifyUser middleware which sets the user object as well. This PR updates the types and allows us to easily use the user object from the controller without have to manually override the types.
Before:
Now:
=> Add type user object to authenticated requests

lib/generate-swagger.js, package.json, test/generate-swagger.test.js, test/generate-types.test.js
In this [PR](https://github.com/lux-group/router/commit/6870ec68e26e310acc75f8b4aa61847def986be7#diff-87e0aedba7aecf461aae9e96921bf7242139b85bde583d84ac62563bbd3bc132) it looks like the way we reference common definitions was changed when upgrading to openspec v3, but looks like one was missed
This ends up with an error when trying to generate types for your api when using a reusable component
=> change reference in response schema

index.d.ts, package.json
When using named strummer matcher, we can generate contract where the body's field is not  payload, but instead use the strummer matcher name:
This PR changes the type definition to allow `req.body` to have the correct typing instead of {} in this case.
=> fix: handler body should allow any string field, not just payload
